import { comfortaa, syne } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "sadra nafe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang = "en" className = {`${syne.variable} ${comfortaa.variable} h-full antialiased`}>
      <body className = "">{children}</body>
    </html>
  );
}
