import Footer from "./components/shared/Footer";
import Navbar from "./components/shared/Navbar";
import { comfortaa, syne } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "sadra nafe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang = "en" className = {`${syne.variable} ${comfortaa.variable} h-full antialiased`}>
      <body className = "bg-neutral-50 text-xs">
        <Navbar/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
